-- Expand transactions table with Phase 4 Task 4.2 spec fields
ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS currency VARCHAR(8) NOT NULL DEFAULT 'INR',
    ADD COLUMN IF NOT EXISTS debit_credit VARCHAR(16) NOT NULL DEFAULT 'debit',
    ADD COLUMN IF NOT EXISTS merchant_name VARCHAR(256) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS merchant_category VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS assigned_category VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS user_notes TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS linked_account VARCHAR(128) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS payment_intent_id VARCHAR(128) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS upi_intent_id VARCHAR(128) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS bank_reference VARCHAR(128) NOT NULL DEFAULT '';
