-- Expand goals table with Phase 4 Task 4.3 spec fields
ALTER TABLE goals
    ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS currency VARCHAR(8) NOT NULL DEFAULT 'INR',
    ADD COLUMN IF NOT EXISTS monthly_contribution_paise BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS frequency VARCHAR(32) NOT NULL DEFAULT 'monthly',
    ADD COLUMN IF NOT EXISTS priority VARCHAR(16) NOT NULL DEFAULT 'medium',
    ADD COLUMN IF NOT EXISTS start_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS linked_account VARCHAR(128) NOT NULL DEFAULT '';
